courses/urls.py
from django.urls import path

from .views import create_course, delete_course, get_courses, update_course

app_name = 'courses'
urlpatterns = [
    path('', get_courses, name='list'),
    path('create/', create_course, name="create"),
    path('update/<int:pk>/', update_course, name="update"),
    path('delete/<int:pk>/', delete_course, name="delete"),


]

lms/urls.py
from django.conf import settings
from django.conf.urls.static import static

from core.views import index

import debug_toolbar

from django.urls import include, path

from django.contrib import admin

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', index, name='index'),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('courses/', include('courses.urls')),
    path('accounts/', include("accounts.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('__debug__/', include(debug_toolbar.urls)),
    path("ckeditor", include("ckeditor_uploader.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
import datetime

from django.db import models

from groups.models import Groups


class Course(models.Model):

    course_name = models.CharField(max_length=30)
    start_date = models.DateField(default=datetime.date.today)
    group = models.OneToOneField(
        Groups,
        on_delete=models.CASCADE,
        null=True,
        related_name='course'
    )

    def __str__(self):
        return f'{self.course_name}'

    # def save(self, *args, **kwargs):
    #     self.start_date = self.group.start_date
    #     super().save(*args, **kwargs)

courses/forms.py
from django import forms

from django_filters import FilterSet

from .models import Course


class CoursesFilter(FilterSet):
    class Meta:
        model = Course
        fields = {
            'course_name': ['exact'],
            'start_date': ['exact'],
            'group': ['exact'],
        }
        widgets = {'start_date': forms.DateInput(attrs={'type': 'date'})}


class CourseCreateForm(forms.ModelForm):
    class Meta:
        model = Course
        exclude = ('start_date',)


class CourseUpdateForm(forms.ModelForm):
    class Meta:
        model = Course
        exclude = ('start_date',)

courses/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from students.models import Students
from .forms import CoursesFilter, CourseCreateForm, CourseUpdateForm

from .models import Course


def get_courses(request):
    courses = Course.objects.all()
    filter_courses = CoursesFilter(data=request.GET, queryset=courses)
    return render(
        request=request,
        template_name='courses/list.html',
        context={"filter_courses": filter_courses}
    )


def create_course(request):
    if request.method == 'GET':
        form = CourseCreateForm()
    elif request.method == 'POST':
        form = CourseCreateForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('courses:list'))
    return render(
        request=request,
        template_name='courses/create.html',
        context={'form': form}
    )


def update_course(request, pk):
    course = Course.objects.get(id=pk)
    if request.method == 'GET':
        form = CourseUpdateForm(instance=course)
    elif request.method == 'POST':
        form = CourseUpdateForm(data=request.POST, instance=course)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('courses:list'))
    return render(
        request=request,
        template_name='courses/update.html',
        context={'form': form}
    )


def delete_course(request, pk):
    course = get_object_or_404(Course, id=pk)
    if request.method == "POST":
        course.delete()
        return HttpResponseRedirect(reverse('courses:list'))

    return render(request, 'courses/groups_confirm_delete.html', {"coure": course})

courses/templates/includes/courses_list_table.html
 <table class="table table-striped table-hover">
        <tr>
            <th></th>
            <th>Name</th>
            <th>Start date</th>
            <th><i class="bi bi-pencil-square"></i></th>
            <th><i class="bi bi-trash"></i></th>
        </tr>


    {% for course in list_object %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{course.course_name}}</td>
            <td>{{course.start_date}}</td>
            <td><a href="{% url 'courses:update' course.id %}">Edit</a></td>
            <td><a href="{% url 'courses:delete' course.id %}">Delete</a></td>
        </tr>
    {% endfor %}
    </table>

courses/templates/includes/courses_search_accordion.html
{% load crispy_forms_tags %}

<div class="accordion" id="accordionExample">
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Search
        </button>
    </h2>
        <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
          <div class="accordion-body">

              <form method="get">
        {{ filter_courses.form | crispy}}
        <input class="btn btn-outline-primary" type="submit" value="Search">
              </form>
          </div>
        </div>
    </div>
</div>