groups/urls.py
from django.urls import path

from .views import GroupDeleteView, GroupUpdateView, GroupListView, GroupCreateView

app_name = 'groups'
urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('create/', GroupCreateView.as_view(), name="create"),
    path('update/<int:pk>/', GroupUpdateView.as_view(), name="update"),
    path('delete/<int:pk>/', GroupDeleteView.as_view(), name="delete"),


]

lms/urls.py
from django.conf import settings
from django.conf.urls.static import static

from core.views import index

import debug_toolbar

from django.urls import include, path

from django.contrib import admin

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', index, name='index'),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('courses/', include('courses.urls')),
    path('accounts/', include("accounts.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('__debug__/', include(debug_toolbar.urls)),
    path("ckeditor", include("ckeditor_uploader.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teachers/urls.py
from django.urls import path

from .views import TeacherDeleteView, TeachersListView, TeacherCreateView, TeacherUpdateView

app_name = 'teachers'
urlpatterns = [
    path('', TeachersListView.as_view(), name='list'),
    path('create/', TeacherCreateView.as_view(), name="create"),
    path('update/<int:pk>/', TeacherUpdateView.as_view(), name="update"),
    path('delete/<int:pk>/', TeacherDeleteView.as_view(), name="delete"),

]

teachers/models.py
import random

from django.db import models

from core.models import Person
# from groups.models import Groups

# from teachers.validators import phone_number_validator


class Teacher(Person):
    specialization = models.CharField(max_length=70)

    # phone_number = models.CharField(
    #     max_length=13,
    #     blank=True,
    #     null=True,
    #     validators=[phone_number_validator]
    # )
    salary = models.PositiveIntegerField(default=1500)

    # group = models.ForeignKey(
    #     "groups.Groups",
    #     on_delete=models.SET_NULL,
    #     null=True,
    #     related_name='teachers'
    # )

    @classmethod
    def _generate(cls):
        teacher = super()._generate()
        teacher.salary = random.randint(700, 5000)
        teacher.specialization = random.choice(['Python', 'Java', 'JS', 'C/C++', 'Rust', 'PHP', "UI/UX"])
        teacher.save()

teachers/forms.py
from django.forms import ChoiceField, MultipleChoiceField

from core.normalizators import normalize_phone

from django import forms

from django_filters import FilterSet


from .models import Teacher


class TeacherBaseForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = '__all__'


class TeacherCreateForm(TeacherBaseForm):
    def __init__(self, *args, **kwargs):
        from groups.models import Groups
        super().__init__(*args, **kwargs)
        self.fields["group_field"] = MultipleChoiceField(
            choices=[(gr.id, str(gr)) for gr in Groups.objects.all()],
            label="Groups",
            required=False
        )

    # class Meta:
    #     exclude =

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        return normalize_phone(phone_number)

    @staticmethod
    def normalize_name(value):
        return value.lower().capitalize()

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        return self.normalize_name(first_name)

    def clean_second_name(self):
        second_name = self.cleaned_data['second_name']
        return self.normalize_name(second_name)


class TeachersFilter(FilterSet):
    class Meta:
        model = Teacher
        fields = {
            "first_name": ["exact"],
            "second_name": ["exact"],
            "birthday": ["exact"],
            # "group": ["exact"]
        }


class TeacherUpdateForm(TeacherBaseForm):

    class Meta:
        model = Teacher
        fields = "__all__"
        # exclude = ['enroll_date', 'graduate_date']

teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView

from groups.models import Groups
from teachers.forms import TeacherCreateForm, TeachersFilter, TeacherUpdateForm
from teachers.models import Teacher


class TeacherUpdateView(LoginRequiredMixin, UpdateView):
    model = Teacher
    form_class = TeacherUpdateForm
    success_url = reverse_lazy('teachers:list')
    template_name = 'teachers/update.html'


class TeachersListView(LoginRequiredMixin, ListView):
    model = Teacher
    template_name = "teachers/list.html"

    def get_queryset(self):
        filter_teachers = TeachersFilter(
            data=self.request.GET,
            queryset=self.model.objects.all())
        # .select_related("group", "headman_group"))

        return filter_teachers


class TeacherDeleteView(LoginRequiredMixin, DeleteView):
    model = Teacher
    success_url = reverse_lazy('teachers:list')


class TeacherCreateView(LoginRequiredMixin, CreateView):
    model = Teacher
    form_class = TeacherCreateForm
    success_url = reverse_lazy("teachers:list")
    template_name = 'teachers/create.html'

    # def form_valid(self, form):
    #     response = super().form_valid(form)
    #     pk = form.cleaned_data["group_field"]
    #     if pk:
    #         form.instance.groups = Groups.objects.filter(id=form.cleaned_data["headman_field"])
    #     form.instance.save()
    #     return response

# def get_teachers(request):
#     teacher = Teacher.objects.all()
#     filter_teachers = TeachersFilter(data=request.GET, queryset=teacher)
#     return render(
#         request=request,
#         template_name='teachers/list.html',
#         context={'filter_teachers': filter_teachers}
#     )
#
#
# def create_teacher(request):
#     if request.method == 'GET':
#         form = TeacherCreateForm()
#     elif request.method == 'POST':
#         form = TeacherCreateForm(data=request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('teachers:list'))
#     return render(
#         request=request,
#         template_name='teachers/create.html',
#         context={'form': form}
#     )
#
#
# def update_teacher(request, pk):
#     teacher = Teacher.objects.get(id=pk)
#     if request.method == 'GET':
#         form = TeacherCreateForm(instance=teacher)
#     elif request.method == 'POST':
#         form = TeacherCreateForm(data=request.POST, instance=teacher)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('teachers:list'))
#     return render(
#         request=request,
#         template_name='teachers/update.html',
#         context={'form': form}
#     )
#
#
# def delete_teacher(request, pk):
#     teacher = get_object_or_404(Teacher, id=pk)
#     if request.method == "POST":
#         teacher.delete()
#         return HttpResponseRedirect(reverse('teachers:list'))
#
#     return render(request, 'teachers/groups_confirm_delete.html', {"teacher": teacher})

teachers/templates/teachers/create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Teacher create
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{form | crispy}}
        <input class="btn btn-outline-success" type="submit" value="Create">
        <a class="btn btn-outline-primary" href="{% url 'groups:list' %}">Cancel</a>&nbsp;&nbsp;&nbsp;
    </form>
{% endblock %}

teachers/templates/teachers/delete.html
{% extends "base.html" %}

{% block tittle %}
    Delete teacher
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Do your really want to remove {{teacher.second_name}} {{teacher.first_name}} </p>
        <input class="btn btn-outline-success" type="submit" value="Agree">
        <a class="btn btn-outline-danger" href="{% url 'teachers:list' %}">Cancel</a>&nbsp;&nbsp;
    </form>
{% endblock %}

teachers/templates/teachers/list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Teachers list
{% endblock %}

{% block content %}

    {% include "includes/teachers_search_accordion.html" %}

    <br>
    <p><strong>Number of teachers: {{ object_list.qs.count }}</strong></p>
    <br>

    {% with list_object=object_list.qs %}
        {% include "includes/teachers_list_table.html" %}
    {% endwith %}

{% endblock %}

teachers/templates/teachers/teacher_confirm_delete.html
{% extends "base.html" %}

{% block tittle %}
    Delete teacher
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Do your really want to remove {{teacher.second_name}} {{teacher.first_name}} </p>
        <input class="btn btn-outline-success" type="submit" value="Agree">
        <a class="btn btn-outline-danger" href="{% url 'teachers:list' %}">Cancel</a>&nbsp;&nbsp;
    </form>
{% endblock %}

teachers/templates/teachers/update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Teacher update
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{form | crispy}}
        <input class="btn btn-outline-success" type="submit" value="Update">
        <a class="btn btn-outline-danger" href="{% url 'teachers:list' %}">Cancel</a>&nbsp;&nbsp;
    </form>

{% endblock %}