accounts/urls.py
from django.urls import path

from accounts.views import AccountRegistrationView, AccountLoginView, AccountLogoutView, AccountUpdateView

app_name = "accounts"

urlpatterns = [
    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name="login"),
    path('logout/', AccountLogoutView.as_view(), name="logout"),
    path('profile/', AccountUpdateView.as_view(), name="profile"),
]

lms/urls.py
from django.conf import settings
from django.conf.urls.static import static

from core.views import index

import debug_toolbar

from django.urls import include, path

from django.contrib import admin

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', index, name='index'),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('courses/', include('courses.urls')),
    path('accounts/', include("accounts.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('__debug__/', include(debug_toolbar.urls)),
    path("ckeditor", include("ckeditor_uploader.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(to=User, on_delete=models.CASCADE)
    birthday = models.DateField(null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    avatar = models.ImageField(null=True, blank=True, default="default.png", upload_to="avatars/")

    def __str__(self):
        return ""


@receiver(post_save, sender=User)
def save_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from accounts.models import Profile


class AccountRegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = [
            "username",
            "first_name",
            "last_name",
            "email"
        ]


class AccountUpdateForm(UserChangeForm):
    password = None

    class Meta(UserCreationForm.Meta):
        fields = ["first_name", "last_name", "email"]


class AccountProfileUpdate(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["birthday", "city", "avatar"]
        widgets = {"birthday": forms.DateInput(attrs={"type": "date"})}

accounts/views.py
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView
from django.views.generic.edit import ProcessFormView

from accounts.forms import AccountRegistrationForm, AccountUpdateForm, AccountProfileUpdate
from django.contrib import messages


class AccountRegistrationView(CreateView):
    model = User
    template_name = "accounts/registration.html"
    success_url = reverse_lazy("index")
    form_class = AccountRegistrationForm


class AccountLoginView(LoginView):
    template_name = "accounts/login.html"

    def get_redirect_url(self):
        next_value = self.request.GET.get("next")
        if next_value:
            return next_value
        return reverse("index")

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, f"User {self.request.user} has successfully logged in")
        return result


class AccountLogoutView(LogoutView):
    template_name = "accounts/logout.html"


class AccountUpdateView(ProcessFormView):
    def get(self, request, *args, **kwargs):
        user = self.request.user
        profile = self.request.user.profile

        user_form = AccountUpdateForm(instance=user)
        profile_form = AccountProfileUpdate(instance=profile)

        return render(
            request,
            "accounts/profile.html",
            context={"user_form": user_form,
                     "profile_form": profile_form}
        )

    def post(self, request, *args, **kwargs):
        user = self.request.user
        profile = self.request.user.profile

        user_form = AccountUpdateForm(instance=user, data=request.POST)
        profile_form = AccountProfileUpdate(instance=profile, data=request.POST, files=request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

            return HttpResponseRedirect(reverse("accounts:profile"))

        return render(
            request,
            "accounts/profile.html",
            context={"user_form": user_form,
                     "profile_form": profile_form}
        )

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
  Login
{% endblock %}

{% block content %}
  <form method = "post">
    {% csrf_token %}
    {{ form | crispy }}
    <a href="{% url 'password_reset' %}">If you forgot a password...</a>
    <div>
      <input class="btn btn-outline-success" type="submit" value="Login">
    <a class="btn btn-outline-danger" href="{% url 'accounts:registration' %}">Registration</a>&nbsp;&nbsp;
  </div>
  </form>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
  Logout
{% endblock %}

{% block content %}
    <a class="btn btn-outline-danger" href="{% url 'accounts:login' %}">Login</a>&nbsp;&nbsp;
    <a class="btn btn-outline-danger" href="{% url 'accounts:registration' %}">Registration</a>&nbsp;&nbsp;

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Account Edit
{% endblock %}

{% block content %}
    <form method ="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div>

            <div class="img-circle.vert">
                <img class="rounded-circle p-1 m-1" width="200" height="200" src="{{user.profile.avatar.url}}">
            </div>

            <div class ="p-3 m-3">
                <h2 class="account-heading"> {{ user.first_name }} {{ user.last_name }}</h2>
                <p class="text-secondary"> {{ user.email }} </p>
            </div>

        </div>
        {{ user_form | crispy }}
        {{ profile_form | crispy }}

        <input class="btn btn-success mt-3" type="submit" value="Save">
        <a class="btn btn-danger mt-3" href="{% url 'index' %}">Cancel</a>
        </form>

{% endblock %}

accounts/templates/accounts/registration.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
  Create account
{% endblock %}

{% block content %}
  <form method = "post">
    {% csrf_token %}
    {{ form | crispy }}
    <input class="btn btn-outline-success" type="submit" value="Register">
    <a class="btn btn-outline-danger" href="{% url 'accounts:login' %}">Login</a>&nbsp;&nbsp;
  </form>
{% endblock %}