lms/urls.py
from django.conf import settings
from django.conf.urls.static import static

from core.views import index

import debug_toolbar

from django.urls import include, path

from django.contrib import admin

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', index, name='index'),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('courses/', include('courses.urls')),
    path('accounts/', include("accounts.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('__debug__/', include(debug_toolbar.urls)),
    path("ckeditor", include("ckeditor_uploader.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path

from .views import StudentCreateView, StudentDeleteView, StudentUpdateView, StudentsListView

app_name = 'students'

urlpatterns = [
    path('', StudentsListView.as_view(), name='list'),
    path('create/', StudentCreateView.as_view(), name="create"),
    path('update/<int:pk>/', StudentUpdateView.as_view(), name="update"),
    path('delete/<int:pk>/', StudentDeleteView.as_view(), name="delete"),

]

students/models.py
import datetime
import random

from faker import Faker

from core.models import Person

from dateutil.relativedelta import relativedelta

from django.db import models


class Students(Person):
    enroll_date = models.DateField(default=datetime.date.today)

    graduate_date = models.DateField(default=datetime.date.today)

    group = models.ForeignKey(
        "groups.Groups",
        on_delete=models.SET_NULL,
        null=True,
        related_name="students"
    )

    def __str__(self):
        return f"{self.first_name} {self.second_name} {self.age} {self.phone_number}"

    def save(self, *args, **kwargs):
        self.age = relativedelta(datetime.date.today(), self.birthday).years
        if self.group:
            self.enroll_date = self.group.start_date
            self.graduate_date = self.enroll_date + datetime.timedelta(days=120)
        super().save(*args, **kwargs)

    @classmethod
    def _generate(cls):
        student = super()._generate()

        from groups.models import Groups
        group = random.choice(list(Groups.objects.all()))

        student.enroll_date = group.start_date
        student.graduate_date = student.enroll_date + datetime.timedelta(days=120)
        student.group = group
        student.save()

students/forms.py
from core.normalizators import normalize_phone

from django import forms

from django_filters import FilterSet

from .models import Students


class StudentBaseForm(forms.ModelForm):
    class Meta:
        model = Students
        fields = "__all__"
        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'}),
            'enroll_date': forms.DateInput(attrs={'type': 'date'})
        }


class StudentCreateForm(StudentBaseForm):
    class Meta:
        model = Students
        fields = "__all__"
        exclude = ['enroll_date', 'graduate_date', "age"]

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        return normalize_phone(phone_number)

    @staticmethod
    def normalize_name(value):
        return value.lower().capitalize()

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        return self.normalize_name(first_name)

    def clean_second_name(self):
        second_name = self.cleaned_data['second_name']
        return self.normalize_name(second_name)


class StudentsFilter(FilterSet):
    class Meta:
        model = Students
        fields = {
            "age": ["lt", "gt"],
            "first_name": ["exact"],
            "second_name": ["exact"],
            "group": ['exact']
        }


class StudentUpdateForm(StudentBaseForm):
    class Meta:
        model = Students
        exclude = ['enroll_date', 'graduate_date']

students/views.py
from copy import copy

from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import UpdateView, ListView, DeleteView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from core.views import UpdateBaseView
from students.models import Students

from .forms import StudentCreateForm, StudentUpdateForm
from .forms import StudentsFilter


class StudentsListView(LoginRequiredMixin, ListView):
    paginate_by = 10
    model = Students
    template_name = "students/list.html"

    def get_filter(self):
        return StudentsFilter(
            data=self.request.GET,
            queryset=self.model.objects.all().select_related("group", "headman_group"))

    def get_queryset(self):
        return self.get_filter().qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter_form"] = self.get_filter().form
    #
    #     params = self.request.GET
    #     if 'page' in params:
    #         params = copy(params)
    #         del params['page']
    #     context['get_params'] = '&' + params.urlencode() if params else ''  # convert dict to str

        return context


class StudentCreateView(LoginRequiredMixin, CreateView):
    model = Students
    form_class = StudentCreateForm
    success_url = reverse_lazy("students:list")
    template_name = 'students/create.html'

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, f"Student was successfully created")
        return result


class StudentUpdateView(LoginRequiredMixin, UpdateView):
    model = Students
    form_class = StudentUpdateForm
    success_url = reverse_lazy('students:list')
    template_name = 'students/update.html'

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, f"Student {self.get_object()} was successfully updated")
        return result


class StudentDeleteView(LoginRequiredMixin, DeleteView):
    model = Students
    success_url = reverse_lazy('students:list')

    def form_valid(self, form):
        student = self.get_object()
        result = super().form_valid(form)
        messages.success(self.request, f"Student {student} was successfully deleted")
        return result

# def get_students(request):
#     students = Students.objects.all().select_related("group", "headman_group")
#     filter_students = StudentsFilter(data=request.GET, queryset=students)
#     return render(
#         request=request,
#         template_name='students/list.html',
#         context={"filter_students": filter_students}
#     )
#
#
# def create_student(request):
#     if request.method == 'GET':
#         form = StudentCreateForm()
#     elif request.method == 'POST':
#         form = StudentCreateForm(data=request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('students:list'))
#     return render(
#         request=request,
#         template_name='students/create.html',
#         context={'form': form}
#     )
#
#
# def update_student(request, pk):
#     student = Students.objects.get(id=pk)
#     if request.method == 'GET':
#         form = StudentCreateForm(instance=student)
#     elif request.method == 'POST':
#         form = StudentCreateForm(data=request.POST, instance=student)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('students:list'))
#     return render(
#         request=request,
#         template_name='students/update.html',
#         context={'form': form}
#     )
#
#
#
# @login_required
# def delete_student(request, pk):
#     student = get_object_or_404(Students, id=pk)
#     if request.method == "POST":
#         student.delete()
#         return HttpResponseRedirect(reverse('students:list'))
#
#     return render(request, 'students/groups_confirm_delete.html', {"student": student})
# #
# #
# # "Ниже реализация Class Based View вручную"
#
#
# class UpdateStudentView(UpdateBaseView):
#     model = Students
#     form_class = StudentUpdateForm
#     success_url = 'students:list'
#     template_name = 'students/update.html'

students/templates/includes/students_list_table.html
 <table class="table table-striped table-hover">
        <tr>
            <th></th>
            <th>First name</th>
            <th>Second name </th>
            <th>Age </th>
            <th>Phone </th>
            <th>Enroll date </th>
            <th>Graduate date </th>
            <th>Group</th>
            <th>Headman</th>
            {% if user.is_authenticated %}
            <th><i class="bi bi-pencil-square"></i></th>
            <th><i class="bi bi-trash"></i></th>
            {% endif %}
        </tr>


    {% for student in list_object %}
        <tr>
            <td>{{forloop.counter0|add:page_obj.start_index }}</td>
            <td>{{student.first_name}}</td>
            <td>{{student.second_name}}</td>
            <td>{{student.age}}</td>
            <td>{% if student.phone_number is not None %}{{student.phone_number}} {% endif %}</td>
            <td>{{student.enroll_date}}</td>
            <td>{{student.graduate_date}}</td>
            <td>{% if student.group is not None %}{{ student.group }} {% endif %}</td>
            <td>{% if student.headman_group %}<i class="bi bi-check-lg"></i>{% endif %}</td>
            {% if user.is_authenticated %}
            <td><a href="{% url 'students:update' student.id %}">Edit</a></td>
            <td><a href="{% url 'students:delete' student.id %}">Delete</a></td>
            {% endif %}
        </tr>
    {% endfor %}
    </table>

students/templates/includes/students_search_accordion.html
{% load crispy_forms_tags %}

<div class="accordion" id="accordionExample">
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Search
        </button>
    </h2>
        <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
          <div class="accordion-body">

              <form method="get">
        {{ filter_form | crispy}}
        <input class="btn btn-outline-primary" type="submit" value="Search">
              </form>
          </div>
        </div>
    </div>
</div>